/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Batchcall, BatchcallInterface } from "../Batchcall";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "batchcall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Batchcall__factory {
  static readonly abi = _abi;
  static createInterface(): BatchcallInterface {
    return new utils.Interface(_abi) as BatchcallInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Batchcall {
    return new Contract(address, _abi, signerOrProvider) as Batchcall;
  }
}
